=head1 Prerequisites

=head3 System

    Ubuntu 11.10 or Ubuntu 12.04

All packages are built and tested against Ubuntu 11.10 and 12.04. While its
entirely possible to run this software on any Linux distro, these instructions
are based on the assumption that you will be installing them on the above
mentioned system/version.

=head3 libiomeme-perl

    libimager-perl
    libmoose-perl

=head3 libiomeme-www

    nginx
    libiomeme-perl
    libmojolicious-perl
    libcache-fastmmap-perl

=head3 Build Time

    make
    fakeroot
    dpkg-deb
    dpkg

=head1 Installation

=head3 libiomeme-perl

    cd libiomeme-perl/
    sudo make install
    
    
=head3 libiomeme-www

    cd libiomeme-www/
    sudo make install

    # The default nginx settings for iomeme listen on port 1337.
    # Update the "listen" parameter in /etc/nginx/sites-available/iomeme if
    # you want something else


=head1 Start services

    sudo service iomeme start
    sudo service nginx start


=head1 Try it out!

    http://localhost:1337/sk/installed+iomeme/it+works!
