=head1 Note

All packages are built and tested against Ubuntu 11.10 and 12.04. While its
entirely possible to run this software on any Linux distro, these instructions
are based on the assumption that you will be installing them on the above
mentioned system/version.

=head1 Prerequisites

=head3 System

    Ubuntu 11.10 or Ubuntu 12.04

=head3 libiomeme-perl

    sudo apt-get install libimager-perl libmoose-perl

=head3 libiomeme-www

    sudo apt-get install nginx libmojolicious-perl libcache-fastmmap-perl


=head1 Installation

If you are installing iomeme using B<make install>, you will need to
have B<make> and B<fakeroot> installed

    sudo apt-get install make fakeroot

=head3 libiomeme-perl

    cd libiomeme-perl/
    sudo make install

=head3 libiomeme-www

The default nginx settings for iomeme listen on port 1337.
Update the B<listen> parameter in /etc/nginx/sites-available/iomeme
if you want something else

    cd libiomeme-www/
    sudo make install

=head1 Start services

    sudo service iomeme start
    sudo service nginx start


=head1 Try it out!

    http://localhost:1337/sk/installed+iomeme/it+works!
