#!/bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/hypnotoad
NAME=iomeme

DAEMON_SCRIPT='/usr/share/nginx/www/iome.me/scripts/iomeme.pl'
DAEMON_START="$DAEMON $DAEMON_SCRIPT"
DAEMON_STOP="$DAEMON --stop $DAEMON_SCRIPT"


test -x $DAEMON || exit 0

set -e

. /lib/lsb/init-functions

case "$1" in
	start)
		echo "Starting $NAME"
                $DAEMON_START

		;;

	stop)
		echo "Stopping $NAME"
                for i in $(ps x | grep iomeme.pl$ | awk '{print $1}')
                do
                    kill -9 $i
                done

		;;

	restart|force-reload)
		echo "Restarting $NAME"

                for i in $(ps x | grep iomeme.pl$ | awk '{print $1}')
                do
                    kill -9 $i
                done

		sleep 1

                $DAEMON_START

		;;

esac

exit 0
